# Site settings
title: Portfolio
email: nornahh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web Developer creating a new awesome personal website using Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
google_username: nornahh

permalink: /:categories/:title

links:
  - title: about
    url: /about
  - title: work
    url: /work
  - title: articles
    url: /articles
  - title: hire mean
    url: /hire-me

# Build settings
markdown: kramdown
