# Site settings
title: Portfolio
email: nornahh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web Developer creating a new awesome personal website using Jekyll.
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
skype_username: yon.brooks
github_username:  Yonald
linkedin_username: yon-brooks-a7536797

permalink: /:categories/:title

links:
  - title: about
    url: /about
  - title: work
    url: /work
  - title: articles
    url: /articles
  - title: hire me
    url: /hire-me

# Build settings
markdown: kramdown

